# Generated by Django 3.2.9 on 2022-04-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipodoc', models.CharField(blank=True, max_length=5, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Editoriales',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'editoriales',
            },
        ),
        migrations.CreateModel(
            name='Ejemplares',
            fields=[
                ('id_ejemplar', models.AutoField(primary_key=True, serialize=False)),
                ('num_ejemplar', models.CharField(blank=True, max_length=3, null=True)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'ejemplares',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipodoc', models.CharField(blank=True, max_length=5, null=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'grados',
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('letra_grupo', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'idiomas',
            },
        ),
        migrations.CreateModel(
            name='TipoInfraccion',
            fields=[
                ('id_tipo_infraccion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'tipo_infraccion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('doc', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Numero de documento')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de usuario')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen del perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('ejemplares', models.ManyToManyField(to='api.Ejemplares')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiantes')),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Prestados',
            fields=[
                ('id_prestado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('id_ejemplar', models.ForeignKey(db_column='id_ejemplar', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ejemplares')),
                ('id_estudiante', models.ForeignKey(blank=True, db_column='id_estudiante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiantes')),
            ],
            options={
                'db_table': 'prestados',
            },
        ),
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('edicion', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_paginas', models.IntegerField(blank=True, null=True)),
                ('alto', models.CharField(blank=True, max_length=5, null=True)),
                ('ancho', models.CharField(blank=True, max_length=5, null=True)),
                ('peso', models.CharField(blank=True, max_length=7, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=30, null=True)),
                ('anexos', models.CharField(blank=True, max_length=200, null=True)),
                ('palabras_clave', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('autores', models.ManyToManyField(to='api.Autores')),
                ('categorias', models.ManyToManyField(to='api.Categorias')),
                ('id_editorial', models.ForeignKey(blank=True, db_column='id_editorial', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.editoriales')),
                ('id_idioma', models.ForeignKey(blank=True, db_column='id_idioma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.idiomas')),
            ],
            options={
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Infracciones',
            fields=[
                ('id_infraccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('ejemplares', models.ManyToManyField(to='api.Ejemplares')),
                ('id_administrador', models.ForeignKey(blank=True, db_column='id_administrador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.administradores')),
                ('id_estudiante', models.ForeignKey(blank=True, db_column='id_estudiante', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiantes')),
                ('id_tipo_infraccion', models.ForeignKey(blank=True, db_column='id_tipo_infraccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tipoinfraccion')),
            ],
            options={
                'db_table': 'infracciones',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiantes')),
                ('libros', models.ManyToManyField(to='api.Libros')),
            ],
            options={
                'db_table': 'favoritos',
            },
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='doc_estudiante',
            field=models.ForeignKey(db_column='doc', on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='id_grado',
            field=models.ForeignKey(blank=True, db_column='id_grado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.grados'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='id_grupo',
            field=models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.grupos'),
        ),
        migrations.AddField(
            model_name='ejemplares',
            name='id_libro',
            field=models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, to='api.libros'),
        ),
        migrations.CreateModel(
            name='DePrestamos',
            fields=[
                ('id_de_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fec_prestamo', models.DateTimeField()),
                ('fec_devolucion', models.DateTimeField()),
                ('estado', models.CharField(max_length=3)),
                ('ejemplares', models.ManyToManyField(to='api.Ejemplares')),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.DO_NOTHING, to='api.administradores')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiantes')),
            ],
            options={
                'db_table': 'de_prestamos',
            },
        ),
        migrations.AddField(
            model_name='administradores',
            name='doc_administrador',
            field=models.ForeignKey(db_column='doc', on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
