# Generated by Django 3.2.9 on 2022-04-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='libros/', verbose_name='Imagen del libro'),
        ),
    ]
