# Generated by Django 4.0.4 on 2022-06-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracciones',
            name='ejemplares',
        ),
        migrations.AddField(
            model_name='infracciones',
            name='id_ejemplar',
            field=models.ForeignKey( on_delete=django.db.models.deletion.DO_NOTHING, to='api.ejemplares'),
        ),
    ]
