# Generated by Django 4.0.3 on 2022-04-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libros_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='imagen',
            new_name='imagen_libro',
        ),
    ]
