# Generated by Django 4.0.4 on 2022-06-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_infracciones_ejemplares_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracciones',
            name='id_ejemplar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ejemplares'),
        ),
    ]
