# Generated by Django 4.0.4 on 2022-06-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_infracciones_id_ejemplar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infracciones',
            name='id_ejemplar',
            field=models.ForeignKey(db_column='id_ejemplar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.ejemplares'),
        ),
    ]
