# Generated by Django 3.2.1 on 2022-06-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_infracciones_id_ejemplar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprestamos',
            name='fec_prestamo',
            field=models.DateTimeField(null=True),
        ),
    ]
