# Generated by Django 4.0.3 on 2022-04-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_imagen_libro_libros_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='imagen_libro',
        ),
    ]
