# Generated by Django 4.0.3 on 2022-04-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_imagen_usuario_imagen_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='imagen',
            new_name='imagen_libro',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen_libro',
            new_name='imagen',
        ),
    ]
