# Generated by Django 4.0.3 on 2022-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_imagen_libros_imagen_libro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinfraccion',
            name='id_tipo_infraccion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
