# Generated by Django 4.0.3 on 2022-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_administradores_bibliotecarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='numero_capitulos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
