# Generated by Django 4.0.3 on 2022-05-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_libros_numero_capitulos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='ancho',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='peso',
        ),
    ]
