# Generated by Django 4.0.3 on 2022-05-19 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_libros_alto_remove_libros_ancho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deprestamos',
            name='id_administrador',
        ),
        migrations.RemoveField(
            model_name='infracciones',
            name='id_administrador',
        ),
        migrations.AddField(
            model_name='deprestamos',
            name='id_bibliotecario',
            field=models.ForeignKey(db_column='id_bibliotecario', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bibliotecarios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infracciones',
            name='id_bilbiotecario',
            field=models.ForeignKey(blank=True, db_column='id_bibliotecario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bibliotecarios'),
        ),
    ]
