# Generated by Django 4.0.3 on 2022-05-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_deprestamos_id_administrador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infracciones',
            old_name='id_bilbiotecario',
            new_name='id_bibliotecario',
        ),
    ]
