# Generated by Django 4.0.3 on 2022-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_id_bilbiotecario_infracciones_id_bibliotecario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='imagen_libro',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Imagen del libro'),
        ),
    ]
