# Generated by Django 4.0.4 on 2022-05-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_id_bilbiotecario_infracciones_id_bibliotecario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestados',
            name='id_ejemplar',
        ),
        migrations.RemoveField(
            model_name='prestados',
            name='id_estudiante',
        ),
        migrations.DeleteModel(
            name='DePrestamos',
        ),
        migrations.DeleteModel(
            name='Prestados',
        ),
    ]
