# Generated by Django 4.0.4 on 2022-05-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_prestados_id_ejemplar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DePrestamos',
            fields=[
                ('id_de_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fec_prestamo', models.DateTimeField()),
                ('estado', models.CharField(max_length=3)),
                ('id_bibliotecario', models.ForeignKey(db_column='id_bibliotecario', on_delete=django.db.models.deletion.DO_NOTHING, to='api.bibliotecarios')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.DO_NOTHING, to='api.estudiantes')),
            ],
            options={
                'db_table': 'de_prestamos',
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fec_devolucion', models.DateTimeField()),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('id_de_prestamo', models.ForeignKey(db_column='id_de_prestamos', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prestamos', to='api.deprestamos')),
                ('id_ejemplar', models.ForeignKey(db_column='id_ejemplar', on_delete=django.db.models.deletion.DO_NOTHING, to='api.ejemplares')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
    ]
