# Generated by Django 4.0.3 on 2022-06-01 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_libros_imagen_libro'),
        ('api', '0016_deprestamos_prestamos'),
    ]

    operations = [
    ]
