# Generated by Django 4.0.3 on 2022-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20220601_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='imagen_libro',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen del libro'),
        ),
    ]
