# Generated by Django 4.0.3 on 2022-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_reservas_fecha_limite_reservas_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Imagen del perfil'),
        ),
    ]
