# Generated by Django 4.0.3 on 2022-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='fec_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
