# Generated by Django 4.0.3 on 2022-06-02 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_prestamos_fec_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deprestamos',
            name='id_bibliotecario',
            field=models.ForeignKey(blank=True, db_column='id_bibliotecario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bibliotecarios'),
        ),
    ]
