# Generated by Django 4.0.3 on 2022-06-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_reservas_fecha_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_evento', models.TextField(blank=True, null=True, verbose_name='Imagen del evento')),
                ('titulo', models.TextField(blank=True, null=True)),
                ('fec_inicio', models.DateField(blank=True, null=True)),
                ('fec_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('id_bibliotecario', models.ForeignKey(blank=True, db_column='id_bibliotecario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bibliotecarios')),
            ],
        ),
    ]
