# Generated by Django 4.0.3 on 2022-06-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_deprestamos_fec_prestamo_and_more'),
        ('api', '0024_eventos'),
    ]

    operations = [
    ]
