# Generated by Django 4.0.3 on 2022-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_prestamos_fec_devolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvEstudiantes',
            fields=[
                ('id_csv', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('csv', models.FileField(upload_to='csv_estudiantes/')),
            ],
            options={
                'db_table': 'csv_estudiantes',
            },
        ),
    ]
