# Generated by Django 4.0.3 on 2022-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_csvestudiantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='infracciones',
            name='fecha_infraccion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
