# Generated by Django 4.0.3 on 2022-06-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_infracciones_fecha_infraccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infracciones',
            name='id_ejemplar',
        ),
        migrations.AddField(
            model_name='infracciones',
            name='id_prestamo',
            field=models.ForeignKey(db_column='id_prestamo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.prestamos'),
        ),
    ]
