# Generated by Django 3.2.1 on 2022-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_usuario_codigo_recuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='seleccionado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
